# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.worldhealthorganization.smart-ot
canonical: http://worldhealthorganization.github.io/smart-ot
name: smart-ot
status: draft
version: 0.2.1
fhirVersion: 4.0.1
date: 2023-04-25
# copyright:
copyrightYear: 2021+
releaseLabel: "CI Build"
title: "WHO SMART Guideline: Surveillance and Outbreak Toolkit_PN"
description: "WHO SMART Guideline: Surveillance and Outbreak Toolkit"
license: CC0-1.0
publisher:
  name: Patricia
  url: http://who.int
email: ndumbip@who.int
# contact:
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true
dependencies:  
  hl7.fhir.uv.sdc: 3.0.0


pages:
  index.xml:
    title: Summary
    changes.xml:
      title: Changes
    dependencies.xml:
      title: Dependencies
    references.xml:
      title: References
    adapting.xml:
      title: Adapting Guidelines for Country use
    license.xml:
      title: License
  # business-requirements.md:
  #   title: Business Requirements
    concepts.xml:
      title: Concepts
    personas.xml:
      title: Generic Personas
    usecases.xml:
      title: User Scenarios
    business_process.xml:
      title: Business Processes
    dictionary.xml:
      title: Data Dictionary
    decision_support.xml:
      title: Decision-support logic
    indicators.xml:
      title: Indicator and Performance Metrics
    requirements.xml:
      title: Functional Requirements
    non-functional-requirements.md:
      title: Non-functional Requirements
  data_exchange.xml:
    title: Data Exchange
    data-models-and-exchange.md:
      title: Data Models and Exchange
    system-actors.md:
      title: System Actors
    sequence-diagrams.md:
      title: Sequence Diagrams
    transactions.md:
      title: Transactions
    indicators-measures.md:
      title: Indicators and Measures
    workflows.xml:
      title: Workflows
    profiles.xml:
      title: Content profiles
    codings.md:
      title: Codings

  deployment.xml:
    title: Deployment
    security_privacy.xml:
      title: Security and Privacy Considerations
    testing.xml: 
      title: Testing
    # test-data.md: 
    #   title: Test Data
    reference-implementations.md: 
      title: Reference Implementations
    downloads.xml: 
      title: Downloads
  # indices.md:
  #   title: Indices
  artifacts.xml: 
    title: Artifact Index
    # maps.md: 
    #   title: Mappings



